import { Injectable, ServiceUnavailableException } from "@nestjs/common";
import { createCipheriv, createDecipheriv, randomBytes } from "crypto";
import { PrismaService } from "../data/prisma.service";
import { Platform, SocialOAuthService } from "./operations.service";
@Injectable() export class SocialConnectionsService {
  constructor(private readonly prisma: PrismaService, private readonly oauth: SocialOAuthService) {}
  private key() { const value = process.env.CREDENTIAL_ENCRYPTION_KEY ?? ""; const key = /^[a-f0-9]{64}$/i.test(value) ? Buffer.from(value, "hex") : Buffer.from(value, "base64"); if (key.length !== 32) throw new ServiceUnavailableException("CREDENTIAL_ENCRYPTION_KEY must be a 32-byte base64 or 64-character hex value"); return key; }
  private encrypt(value: unknown) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", this.key(), iv); const encrypted = Buffer.concat([cipher.update(JSON.stringify(value), "utf8"), cipher.final()]); return [iv.toString("base64url"), cipher.getAuthTag().toString("base64url"), encrypted.toString("base64url")].join("."); }
  decrypt(value: string) { const [iv, tag, encrypted] = value.split("."); const decipher = createDecipheriv("aes-256-gcm", this.key(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(encrypted, "base64url")), decipher.final()]).toString("utf8")) as { accessToken: string; refreshToken?: string }; }
  async complete(state: string, code: string, redirectUri: string) { const verified = this.oauth.verify(state); const token = await this.exchange(verified.platform, code, redirectUri); const accountName = await this.accountName(verified.platform, token.access_token); const expiresAt = token.expires_in ? new Date(Date.now() + Number(token.expires_in) * 1000) : null; return this.prisma.socialConnection.upsert({ where: { tenantId_platform_accountName: { tenantId: verified.tenantId, platform: verified.platform as any, accountName } }, create: { tenantId: verified.tenantId, platform: verified.platform as any, accountName, encryptedToken: this.encrypt({ accessToken: token.access_token, refreshToken: token.refresh_token }), expiresAt }, update: { encryptedToken: this.encrypt({ accessToken: token.access_token, refreshToken: token.refresh_token }), expiresAt } }); }
  private async exchange(platform: Platform, code: string, redirectUri: string): Promise<{ access_token: string; refresh_token?: string; expires_in?: number }> { const endpoint = platform === "LINKEDIN" ? "https://www.linkedin.com/oauth/v2/accessToken" : platform === "X" ? "https://api.x.com/2/oauth2/token" : platform === "TIKTOK" ? "https://open.tiktokapis.com/v2/oauth/token/" : platform === "YOUTUBE" ? "https://oauth2.googleapis.com/token" : `https://graph.facebook.com/${process.env.META_GRAPH_VERSION ?? "v22.0"}/oauth/access_token`; const secret = process.env[`${platform}_OAUTH_CLIENT_SECRET`]; const id = process.env[`${platform}_OAUTH_CLIENT_ID`]; if (!secret || !id) throw new ServiceUnavailableException(`${platform} OAuth client credentials are required`); const body = new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: redirectUri, client_id: id, client_secret: secret }); const res = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }); if (!res.ok) throw new Error(`OAuth token exchange failed: ${res.status} ${await res.text()}`); return res.json() as any; }
  private async accountName(platform: Platform, accessToken: string) { const endpoint = platform === "LINKEDIN" ? "https://api.linkedin.com/v2/userinfo" : platform === "X" ? "https://api.x.com/2/users/me" : platform === "TIKTOK" ? "https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name" : platform === "YOUTUBE" ? "https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true" : `https://graph.facebook.com/${process.env.META_GRAPH_VERSION ?? "v22.0"}/me?fields=id,name`; const res = await fetch(endpoint, { headers: { Authorization: `Bearer ${accessToken}` } }); if (!res.ok) throw new Error(`OAuth account lookup failed: ${res.status}`); const data = await res.json() as any; return String(data.name ?? data.sub ?? data.data?.username ?? data.data?.user?.open_id ?? data.items?.[0]?.snippet?.title ?? data.items?.[0]?.id ?? data.id); }
}
