"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "../../lib/api";

export default function WorkspacePage() {
  const { tenantId } = useParams<{ tenantId: string }>();
  const [data, setData] = useState<any>(); const [error, setError] = useState("");
  useEffect(() => { api<any>(`/tenants/${tenantId}/dashboard`).then(setData).catch(e => setError(e.message)); }, [tenantId]);
  if (error) return <main className="formPage"><div className="formCard"><p className="error">{error}</p><Link href="/onboarding">Create another workspace</Link></div></main>;
  if (!data) return <main className="formPage"><div className="formCard"><p>Loading workspace…</p></div></main>;
  return <main className="workspacePage"><header className="workspaceHeader"><div><p className="eyebrow">AGENCY WORKSPACE</p><h1>{data.tenant.name}</h1><p className="sub">{data.tenant.website || "Connect your property website to begin."}</p></div><Link className="primary" href={`/workspace/${tenantId}/properties`}>Add property</Link></header><nav className="workspaceNav"><Link href={`/workspace/${tenantId}`}>Overview</Link><Link href={`/workspace/${tenantId}/properties`}>Properties</Link><Link href={`/workspace/${tenantId}/campaigns`}>Campaigns</Link><Link href={`/workspace/${tenantId}/brand`}>Brand profile</Link></nav><section className="metrics"><div className="metric"><p>Active properties</p><strong>{data.metrics.activeProperties}</strong></div><div className="metric"><p>Campaigns</p><strong>{data.metrics.totalCampaigns}</strong></div><div className="metric attention"><p>Awaiting approval</p><strong>{data.metrics.awaitingApproval}</strong></div></section><div className="workspaceGrid"><section className="panel"><div className="panelHead"><div><p className="eyebrow">LISTINGS</p><h2>Recent properties</h2></div><Link className="link" href={`/workspace/${tenantId}/properties`}>Manage</Link></div>{data.properties.length === 0 ? <p className="empty">No properties yet. Add one manually or import your website feed.</p> : data.properties.map((property: any) => <div className="listRow" key={property.id}><div><strong>{property.title}</strong><small>{property.address}</small></div><span className="pill p2">{property.status}</span></div>)}</section><section className="panel"><div className="panelHead"><div><p className="eyebrow">CAMPAIGNS</p><h2>Latest work</h2></div><Link className="link" href={`/workspace/${tenantId}/campaigns`}>View all</Link></div>{data.campaigns.length === 0 ? <p className="empty">Campaigns will appear after a listing enters the AI workflow.</p> : data.campaigns.slice(0, 5).map((campaign: any) => <div className="listRow" key={campaign.id}><div><strong>{campaign.property?.title || "Property campaign"}</strong><small>{campaign.status} · {campaign.content?.length || 0} assets</small></div><span className="pill p0">{campaign.status}</span></div>)}</section></div></main>;
}
